blaze_traiding/urls.py
from django.contrib import admin
from django.urls import path, include
from django.utils import timezone

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('product.path_urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]
handler404 = 'product.views.handlers.handler404'
handler500 = 'product.views.handlers.handler500'
handler503 = 'product.views.handlers.handler503'

core/urls.py
from django.urls import path
from core.views import HomeView, CashView, cash, cash_buy, start_work, end_work, add_product, remove_product, MyCompany, \
    DutyTemplateView, ExpenseTemplateView, ProductExpenseTemplateView, UsersAnalyticView, SalesListView, \
    CashAnalyticView, update_start_sum, set_cash

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('cash/', CashView.as_view(), name='cash'),
    path('cash/realtime/', cash, name='realtime-cash'),
    path('cash/buy/', cash_buy, name='buy-cash'),
    path('cash/add_product/', add_product, name='add_product-cash'),
    path('cash/remove_product/', remove_product, name='remove_product-cash'),
    path('cash/start_work/', start_work, name='start_work-cash'),
    path('cash/end_work/', end_work, name='end_work-cash'),

    path('company/', MyCompany.as_view(), name='my_company'),
    path('duty/', DutyTemplateView.as_view(), name='duty'),

    path('expenses/', ExpenseTemplateView.as_view(), name='expenses'),
    path('expenses/product/', ProductExpenseTemplateView.as_view(), name='expenses_product'),

    path('user/analytic/', UsersAnalyticView.as_view(), name='user_analytic'),
    path('sales/analytic/', SalesListView.as_view(), name='sales'),
    path('cashes/analytic/', CashAnalyticView.as_view(), name='cashes'),

    path('update/start/sum/', update_start_sum, name='update_start_sum'),
    path('cash/set/', set_cash, name='set_cash'),
]

product/models.py
from datetime import datetime
from django.db import models

from core.models import Balance, Cash
from core.utils import SingletonModel
from user.models import User


class Warehouse(models.Model):
    title = models.CharField(
        verbose_name='Название',
        max_length=255
    )
    address = models.CharField(
        verbose_name='Адресс (необязательно)',
        max_length=255,
        null=True,
        blank=True
    )
    phone = models.CharField(
        verbose_name='Телефон (необязательно)',
        max_length=255,
        null=True,
        blank=True
    )
    comment = models.TextField(
        verbose_name='Комментарий (необязательно)',
        null=True,
        blank=True
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Склад'
        verbose_name_plural = 'Склады'


class Product(models.Model):
    class Unit(models.TextChoices):
        unit = 'unit', 'шт.'
        killogram = 'kg', 'кг.'
        liter = 'lt', 'л.'

    article = models.CharField(
        verbose_name='Артикуль',
        max_length=255,
        unique=True
    )
    title = models.CharField(
        verbose_name='Название',
        max_length=255
    )
    unit = models.CharField(
        verbose_name='Единица измерения',
        choices=Unit.choices,
        default='unit',
        max_length=255
    )
    retail_price = models.FloatField(
        verbose_name='Цена в розницу',
        default=0
    )
    wholesale_price = models.FloatField(
        verbose_name='Цена оптом',
        default=0
    )
    difference = models.FloatField(
        verbose_name='Разница',
        default=0
    )
    purchased = models.PositiveIntegerField(
        verbose_name='Куплено',
        default=0
    )
    remainder = models.IntegerField(
        verbose_name='Общее количество',
        default=0
    )

    def __str__(self):
        return f"{self.title} - {self.article}"

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.remainder = sum([x.count for x in self.deliveries.all()]) - self.purchased - sum(
            [x.return_count for x in self.returns.all()])
        self.difference = self.retail_price - self.wholesale_price
        product_count = ProductCountMessage.objects.first()
        super().save(force_insert=False, force_update=False, using=None,
                     update_fields=None)
        if self.messages.all() and self.remainder >= (product_count.count if product_count else 45):
            self.messages.all().delete()
        if self.remainder <= (product_count.count if product_count else 45):
            Message.objects.get_or_create(product_id=self.id, defaults={
                'product_id': self.id,
                'title': "Нехватка продуктов !",
                "content": f"На складе осталось всего {self.remainder} {self.get_unit_display()} {self.title} \n нужно пополнить запасы !"
            })

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Delivery(models.Model):
    product = models.ForeignKey(
        Product,
        verbose_name='Продукт',
        on_delete=models.CASCADE,
        related_name='deliveries'
    )
    count = models.PositiveIntegerField(
        verbose_name='Количество',
        default=0
    )
    created = models.DateTimeField(
        verbose_name='Время завоза',
        default=datetime.now,
        null=True,
        blank=True
    )
    warehouse = models.ForeignKey(
        to=Warehouse,
        verbose_name='Склад',
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self):
        return f"{self.product.title} | {self.count} | {self.created}"

    class Meta:
        verbose_name = 'Завоз товара'
        verbose_name_plural = 'Завозы товаров'


class ProductCount(models.Model):
    product = models.ForeignKey(
        Product,
        verbose_name='Продукт',
        on_delete=models.CASCADE,
        related_name='product_count'
    )
    kg = models.FloatField(
        verbose_name='Масса',
        default=0
    )
    count = models.IntegerField(
        verbose_name='Количество ',
        default=0
    )

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.product.purchased += self.count
        self.product.remainder -= self.count
        self.product.save()
        super().save(force_insert=False, force_update=False, using=None,
                     update_fields=None)

    def __str__(self):
        return str(self.count)

    class Meta:
        verbose_name = 'Количество Продукт'
        verbose_name_plural = 'Количество Продукты'


class Sale(models.Model):
    class PaymentTypeChoices(models.TextChoices):
        classic = 'classic', 'Наличкой'
        card = 'card', 'Картой'

    products = models.ManyToManyField(
        to=ProductCount,
        verbose_name='Продукты',
        related_name='sales'
    )
    payment_type = models.CharField(
        verbose_name='Тип оплаты',
        max_length=10,
        choices=PaymentTypeChoices.choices
    )
    amount = models.FloatField(
        verbose_name='Общая сумма',
        default=0
    )
    cash = models.ForeignKey(
        'core.Cash',
        verbose_name='Касса',
        on_delete=models.SET_NULL,
        null=True
    )
    created = models.DateField(
        verbose_name='Создано',
        auto_now_add=True,
        null=True,
        blank=True
    )

    def __str__(self):
        return f"{str(self.created)}"

    class Meta:
        verbose_name = 'Продажа'
        verbose_name_plural = 'Продажи'


class ProductReturn(models.Model):
    product = models.ForeignKey(
        Product,
        verbose_name='Продукт',
        on_delete=models.CASCADE,
        related_name='returns'
    )
    return_count = models.PositiveIntegerField(
        verbose_name='Количество',
        default=0
    )
    created = models.DateTimeField(
        verbose_name='Время возврата'
    )
    warehouse = models.ForeignKey(
        to=Warehouse,
        verbose_name='Склад',
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self):
        return str(self.return_count)

    class Meta:
        verbose_name = 'Возврат товара'
        verbose_name_plural = 'Возврат товара'


### Доп. настройки пользователя
class ProductCountMessage(SingletonModel):
    count = models.PositiveIntegerField(
        verbose_name='При каком количестве товара уведомлять вас о его нехватке',
        default=45
    )

    def __str__(self):
        return str(self.count)

    class Meta:
        verbose_name = 'Уведомление при каком количестве товаров'
        verbose_name_plural = 'Уведомление при каком количетве товаров'


class Theme(models.Model):
    class ThemeChoices(models.TextChoices):
        dark = 'dark', 'Темная тема'
        white = 'light', 'Светлая тема'

    user = models.ForeignKey(
        User,
        verbose_name='пользователь',
        on_delete=models.CASCADE
    )
    theme = models.CharField(
        verbose_name='Тема системы',
        choices=ThemeChoices.choices,
        default='light',
        max_length=255
    )


class Message(models.Model):
    title = models.CharField(verbose_name='Заголовок', max_length=255)
    product = models.ForeignKey(
        to=Product,
        verbose_name='Продукт',
        related_name='messages',
        on_delete=models.CASCADE
    )
    content = models.TextField(
        verbose_name='Содержание',
    )

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = 'Уведомление'
        verbose_name_plural = 'Уведомления'


class StartSum(models.Model):
    cash = models.ForeignKey(
        Cash,
        verbose_name='Касса',
        on_delete=models.CASCADE
    )
    amount = models.FloatField(
        verbose_name='Начальная сумма'
    )

    def __str__(self):
        return self.amount

    class Meta:
        verbose_name = 'Начальная сумма в кассе'
        verbose_name_plural = 'Начальная сумма в кассе'


class CustomManager(models.Manager):
    def get_or_create(self, defaults=None, **kwargs):
        obj, created = super().get_or_create(defaults, **kwargs)
        total = 0
        products = Product.objects.all()
        for product in products:
            total += product.retail_price * product.remainder
        obj.amount = total
        obj.save()
        return obj, created


class TurnOver(models.Model):
    amount = models.FloatField(
        verbose_name='Сумма',
        default=0
    )
    objects = CustomManager()

    def __str__(self):
        return str(self.amount)

    class Meta:
        verbose_name = 'Общий оборот'
        verbose_name_plural = 'Общий оборот'

templates/analytic/sales.html
{% extends 'layout/base.html' %}
{% load static widget_tweaks custom_tags %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'vendor/select2/css/select2.min.css' %}">
    <style>
        .select2-selection {
            text-align: center;
            font-size: 20px;
            width: 200px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="content-body">
        <!-- row -->
        <div class="container-fluid">
            <div class="row page-titles mx-0">
                <div class="col-sm-6 p-md-0">
                    <div class="welcome-text">
                        <h4>Список продаж</h4>
                        <span>Полный список ваших продаж</span>
                    </div>
                </div>
                <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                        <li class="breadcrumb-item"><a href="">Аналитика</a></li>
                        <li class="breadcrumb-item"><a href="{{ request.path }}">Продажи</a></li>
                    </ol>
                </div>
            </div>
            <div class="row">

                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Продажи</h4>
                            <form method="get">
                                <select id="single-select" name="product" onchange="this.form.submit()">
                                    <option value="" selected> ---------</option>
                                    {% if product.id %}
                                        <option value="{{ product.id }}" selected>{{ product.title }}</option>
                                    {% endif %}
                                    {% for product in products %}
                                        <option value="{{ product.id }}">{{ product.title }}</option>
                                    {% endfor %}
                                </select>
                            </form>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="example" class="display" style="width:100%">
                                    <thead>
                                    <tr>
                                        <th>
                                            #
                                        </th>
                                        <th><strong>Продукты</strong></th>
                                        <th><strong>Тип оплаты</strong></th>
                                        <th><strong>Общая сумма</strong></th>
                                        <th><strong>Касса</strong></th>
                                        <th><strong>Дата</strong></th>
                                        <th><strong>Действие</strong></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for sale in sales %}
                                        <tr>
                                        <td>
                                            {{ forloop.counter }}
                                        </td>
                                        <td style="width: 200px;">

                                            <button type="button" class="btn btn-success" data-toggle="modal"
                                                    data-target="#basicModal{{ forloop.counter }}">
                                                Просмотреть <i class="fa fa-eye"></i>
                                            </button>
                                            <!-- Modal -->
                                            <div class="modal fade" id="basicModal{{ forloop.counter }}">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title">Список продуктов</h5>
                                                            <button type="button" class="close"
                                                                    data-dismiss="modal">
                                                                <span>&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <div class="row" id="products_modal">
                                                                <table class="table table-bordered">
                                                                    <thead>
                                                                    <th>Название</th>
                                                                    <th>Количество</th>
                                                                    <th>Сумма</th>
                                                                    </thead>
                                                                    <tbody>
                                                                    {% for product in sale.products.all %}
                                                                        <tr>
                                                                            <td>{{ product.product.title }}</td>
                                                                            <td>{{ product.count }}</td>
                                                                            <td>{% multiply product.product.retail_price product.count %}</td>
                                                                        </tr>
                                                                    {% endfor %}
                                                                    </tbody>
                                                                </table>
                                                            </div>

                                                        </div>
                                                        <div class="modal-footer">

                                                            <h5 class="float-left">Общая
                                                                сумма: {{ sale.amount }} сум</h5>

                                                        </div>
                                                    </div>

                                                </div>
                                            </div>

                                        </td>
                                        <td>{{ sale.get_payment_type_display }}</td>
                                        <td>{{ sale.amount }}</td>
                                        <td>Касса №{{ sale.cash.id }}</td>
                                        <td>{{ sale.created }}</td>
                                        <td>
                                            <button type="button" class="btn btn-danger" data-toggle="modal"
                                                    data-target="#basicModal_1_{{ forloop.counter }}">
                                                Удалить <i class="fa fa-eye"></i>
                                            </button>
                                            <!-- Modal -->
                                            <form action="{{ request.path }}" method="post">
                                                {% csrf_token %}
                                                <input type="hidden" name="delete" value="yes">
                                                <input type="hidden" name="id" value="{{ sale.id }}">
                                                <div class="modal fade" id="basicModal_1_{{ forloop.counter }}">
                                                    <div class="modal-dialog" role="document">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title">Удаление</h5>
                                                                <button type="button" class="close"
                                                                        data-dismiss="modal">
                                                                    <span>&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <h1>Вы уверены что хотите удалить продажу ?</h1>
                                                            </div>
                                                            <div class="modal-footer">

                                                                <button type="button" class="btn btn-success"
                                                                        data-dismiss="modal">
                                                                    <span>Отмена</span>
                                                                </button>
                                                                <button type="submit" class="btn btn-danger">
                                                                    <span>Удалить</span>
                                                                </button>

                                                            </div>
                                                        </div>

                                                    </div>
                                                </div>
                                            </form>
                                        </td>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <!-- Datatable -->
    <script src="{% static 'vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/plugins-init/datatables.init.js' %}"></script>
    <script src="{% static 'vendor/select2/js/select2.full.min.js' %}"></script>
    <script src="{% static 'js/plugins-init/select2-init.js' %}"></script>

    {#    <script>#}
    {#        function click() {#}
    {#            swal({#}
    {#                title: "Are you sure to delete ?",#}
    {#                text: "You will not be able to recover this imaginary file !!",#}
    {#                type: "warning",#}
    {#                showCancelButton: !0,#}
    {#                confirmButtonColor: "#DD6B55",#}
    {#                confirmButtonText: "Yes, delete it !!",#}
    {#                cancelButtonText: "No, cancel it !!",#}
    {#                closeOnConfirm: !1,#}
    {#                closeOnCancel: !1#}
    {#            }, function (e) {#}
    {#                e ? swal("Deleted !!", "Hey, your imaginary file has been deleted !!", "success") : swal("Cancelled !!", "Hey, your imaginary file is safe !!", "error")#}
    {#            })#}
    {#        }#}
    {#    </script>#}
    {#    <script src="{% static 'js/plugins-init/sweetalert.init.js' %}"></script>#}
    {#    <script>#}
    {#        document.querySelector(".sweet-wrong").onclick = function () {#}
    {#            sweetAlert("Oops...", "Something went wrong !!", "error")#}
    {#        }#}
    {#    </script>#}
{% endblock %}