blaze_traiding/urls.py
from django.contrib import admin
from django.urls import path, include
from django.utils import timezone

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('product.path_urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]
handler404 = 'product.views.handlers.handler404'
handler500 = 'product.views.handlers.handler500'
handler503 = 'product.views.handlers.handler503'

core/urls.py
from django.urls import path
from core.views import HomeView, CashView, cash, cash_buy, start_work, end_work, add_product, remove_product, MyCompany, \
    DutyTemplateView, ExpenseTemplateView, ProductExpenseTemplateView, UsersAnalyticView, SalesListView, \
    CashAnalyticView, update_start_sum, set_cash

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('cash/', CashView.as_view(), name='cash'),
    path('cash/realtime/', cash, name='realtime-cash'),
    path('cash/buy/', cash_buy, name='buy-cash'),
    path('cash/add_product/', add_product, name='add_product-cash'),
    path('cash/remove_product/', remove_product, name='remove_product-cash'),
    path('cash/start_work/', start_work, name='start_work-cash'),
    path('cash/end_work/', end_work, name='end_work-cash'),

    path('company/', MyCompany.as_view(), name='my_company'),
    path('duty/', DutyTemplateView.as_view(), name='duty'),

    path('expenses/', ExpenseTemplateView.as_view(), name='expenses'),
    path('expenses/product/', ProductExpenseTemplateView.as_view(), name='expenses_product'),

    path('user/analytic/', UsersAnalyticView.as_view(), name='user_analytic'),
    path('sales/analytic/', SalesListView.as_view(), name='sales'),
    path('cashes/analytic/', CashAnalyticView.as_view(), name='cashes'),

    path('update/start/sum/', update_start_sum, name='update_start_sum'),
    path('cash/set/', set_cash, name='set_cash'),
]

product/models.py
from datetime import datetime
from django.db import models

from core.models import Balance, Cash
from core.utils import SingletonModel
from user.models import User


class Warehouse(models.Model):
    title = models.CharField(
        verbose_name='Название',
        max_length=255
    )
    address = models.CharField(
        verbose_name='Адресс (необязательно)',
        max_length=255,
        null=True,
        blank=True
    )
    phone = models.CharField(
        verbose_name='Телефон (необязательно)',
        max_length=255,
        null=True,
        blank=True
    )
    comment = models.TextField(
        verbose_name='Комментарий (необязательно)',
        null=True,
        blank=True
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Склад'
        verbose_name_plural = 'Склады'


class Product(models.Model):
    class Unit(models.TextChoices):
        unit = 'unit', 'шт.'
        killogram = 'kg', 'кг.'
        liter = 'lt', 'л.'

    article = models.CharField(
        verbose_name='Артикуль',
        max_length=255,
        unique=True
    )
    title = models.CharField(
        verbose_name='Название',
        max_length=255
    )
    unit = models.CharField(
        verbose_name='Единица измерения',
        choices=Unit.choices,
        default='unit',
        max_length=255
    )
    retail_price = models.FloatField(
        verbose_name='Цена в розницу',
        default=0
    )
    wholesale_price = models.FloatField(
        verbose_name='Цена оптом',
        default=0
    )
    difference = models.FloatField(
        verbose_name='Разница',
        default=0
    )
    purchased = models.PositiveIntegerField(
        verbose_name='Куплено',
        default=0
    )
    remainder = models.IntegerField(
        verbose_name='Общее количество',
        default=0
    )

    def __str__(self):
        return f"{self.title} - {self.article}"

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.remainder = sum([x.count for x in self.deliveries.all()]) - self.purchased - sum(
            [x.return_count for x in self.returns.all()])
        self.difference = self.retail_price - self.wholesale_price
        product_count = ProductCountMessage.objects.first()
        super().save(force_insert=False, force_update=False, using=None,
                     update_fields=None)
        if self.messages.all() and self.remainder >= (product_count.count if product_count else 45):
            self.messages.all().delete()
        if self.remainder <= (product_count.count if product_count else 45):
            Message.objects.get_or_create(product_id=self.id, defaults={
                'product_id': self.id,
                'title': "Нехватка продуктов !",
                "content": f"На складе осталось всего {self.remainder} {self.get_unit_display()} {self.title} \n нужно пополнить запасы !"
            })

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Delivery(models.Model):
    product = models.ForeignKey(
        Product,
        verbose_name='Продукт',
        on_delete=models.CASCADE,
        related_name='deliveries'
    )
    count = models.PositiveIntegerField(
        verbose_name='Количество',
        default=0
    )
    created = models.DateTimeField(
        verbose_name='Время завоза',
        default=datetime.now,
        null=True,
        blank=True
    )
    warehouse = models.ForeignKey(
        to=Warehouse,
        verbose_name='Склад',
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self):
        return f"{self.product.title} | {self.count} | {self.created}"

    class Meta:
        verbose_name = 'Завоз товара'
        verbose_name_plural = 'Завозы товаров'


class ProductCount(models.Model):
    product = models.ForeignKey(
        Product,
        verbose_name='Продукт',
        on_delete=models.CASCADE,
        related_name='product_count'
    )
    kg = models.FloatField(
        verbose_name='Масса',
        default=0
    )
    count = models.IntegerField(
        verbose_name='Количество ',
        default=0
    )

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.product.purchased += self.count
        self.product.remainder -= self.count
        self.product.save()
        super().save(force_insert=False, force_update=False, using=None,
                     update_fields=None)

    def __str__(self):
        return str(self.count)

    class Meta:
        verbose_name = 'Количество Продукт'
        verbose_name_plural = 'Количество Продукты'


class Sale(models.Model):
    class PaymentTypeChoices(models.TextChoices):
        classic = 'classic', 'Наличкой'
        card = 'card', 'Картой'

    products = models.ManyToManyField(
        to=ProductCount,
        verbose_name='Продукты',
        related_name='sales'
    )
    payment_type = models.CharField(
        verbose_name='Тип оплаты',
        max_length=10,
        choices=PaymentTypeChoices.choices
    )
    amount = models.FloatField(
        verbose_name='Общая сумма',
        default=0
    )
    cash = models.ForeignKey(
        'core.Cash',
        verbose_name='Касса',
        on_delete=models.SET_NULL,
        null=True
    )
    created = models.DateField(
        verbose_name='Создано',
        auto_now_add=True,
        null=True,
        blank=True
    )

    def __str__(self):
        return f"{str(self.created)}"

    class Meta:
        verbose_name = 'Продажа'
        verbose_name_plural = 'Продажи'


class ProductReturn(models.Model):
    product = models.ForeignKey(
        Product,
        verbose_name='Продукт',
        on_delete=models.CASCADE,
        related_name='returns'
    )
    return_count = models.PositiveIntegerField(
        verbose_name='Количество',
        default=0
    )
    created = models.DateTimeField(
        verbose_name='Время возврата'
    )
    warehouse = models.ForeignKey(
        to=Warehouse,
        verbose_name='Склад',
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self):
        return str(self.return_count)

    class Meta:
        verbose_name = 'Возврат товара'
        verbose_name_plural = 'Возврат товара'


### Доп. настройки пользователя
class ProductCountMessage(SingletonModel):
    count = models.PositiveIntegerField(
        verbose_name='При каком количестве товара уведомлять вас о его нехватке',
        default=45
    )

    def __str__(self):
        return str(self.count)

    class Meta:
        verbose_name = 'Уведомление при каком количестве товаров'
        verbose_name_plural = 'Уведомление при каком количетве товаров'


class Theme(models.Model):
    class ThemeChoices(models.TextChoices):
        dark = 'dark', 'Темная тема'
        white = 'light', 'Светлая тема'

    user = models.ForeignKey(
        User,
        verbose_name='пользователь',
        on_delete=models.CASCADE
    )
    theme = models.CharField(
        verbose_name='Тема системы',
        choices=ThemeChoices.choices,
        default='light',
        max_length=255
    )


class Message(models.Model):
    title = models.CharField(verbose_name='Заголовок', max_length=255)
    product = models.ForeignKey(
        to=Product,
        verbose_name='Продукт',
        related_name='messages',
        on_delete=models.CASCADE
    )
    content = models.TextField(
        verbose_name='Содержание',
    )

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = 'Уведомление'
        verbose_name_plural = 'Уведомления'


class StartSum(models.Model):
    cash = models.ForeignKey(
        Cash,
        verbose_name='Касса',
        on_delete=models.CASCADE
    )
    amount = models.FloatField(
        verbose_name='Начальная сумма'
    )

    def __str__(self):
        return self.amount

    class Meta:
        verbose_name = 'Начальная сумма в кассе'
        verbose_name_plural = 'Начальная сумма в кассе'


class CustomManager(models.Manager):
    def get_or_create(self, defaults=None, **kwargs):
        obj, created = super().get_or_create(defaults, **kwargs)
        total = 0
        products = Product.objects.all()
        for product in products:
            total += product.retail_price * product.remainder
        obj.amount = total
        obj.save()
        return obj, created


class TurnOver(models.Model):
    amount = models.FloatField(
        verbose_name='Сумма',
        default=0
    )
    objects = CustomManager()

    def __str__(self):
        return str(self.amount)

    class Meta:
        verbose_name = 'Общий оборот'
        verbose_name_plural = 'Общий оборот'

product/forms.py
from django.forms import ModelForm

from product.models import Warehouse, Product, Delivery, ProductReturn, ProductCountMessage


class WarehouseModelForm(ModelForm):
    class Meta:
        model = Warehouse
        fields = '__all__'


class ProductModelForm(ModelForm):
    class Meta:
        model = Product
        exclude = 'difference', 'purchased', 'remainder'


class DeliveryModelForm(ModelForm):
    class Meta:
        model = Delivery
        exclude = 'product',


class ProductReturnForm(ModelForm):
    class Meta:
        model = ProductReturn
        exclude = 'product',

class ProductCountMessageModelForm(ModelForm):
    class Meta:
        model = ProductCountMessage
        fields = '__all__'

product/views/handlers.py
from django.shortcuts import render


def handler404(request, *args, **argv):
    response = render('404.html', {}, )
    return response

def handler503(request, *args, **argv):
    response = render('503.html', {}, )
    return response

def handler500(request, *args, **argv):
    response = render('503.html', {}, )
    return response

product/views/warehouse_views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView

from product.forms import WarehouseModelForm
from product.models import Warehouse


class WarehouseListView(ListView):
    model = Warehouse
    fields = '__all__'
    template_name = 'warehouse/warehouse.html'
    context_object_name = 'warehouse'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WarehouseListView, self).get_context_data(object_list=None, **kwargs)
        context['form'] = WarehouseModelForm()
        return context

    def post(self, request):
        if 'delete' in request.POST:
            instance = Warehouse.objects.filter(id=request.POST.get('id')).first()
            if instance:
                instance.delete()
        elif 'id' in request.POST:
            instance = Warehouse.objects.get(id=request.POST.get('id'))
            form = WarehouseModelForm(request.POST, instance=instance)
            if form.is_valid():
                form.save()
        else:
            form = WarehouseModelForm(request.POST)
            if form.is_valid():
                form.save()
        qs = self.get_queryset()
        return redirect(reverse_lazy('warehouse'))


class WarehouseDetailView(DetailView):
    model = Warehouse
    fields = '__all__'
    template_name = 'warehouse/products.html'
    context_object_name = 'warehouse'

templates/products/product.html
{% extends 'layout/base.html' %}
{% load static widget_tweaks custom_tags %}
{% block content %}
    <div class="content-body">
        <!-- row -->
        <div class="container-fluid">
            <div class="row page-titles mx-0">
                <div class="col-sm-6 p-md-0">
                    <div class="welcome-text">
                        <h4>Список товаров</h4>
                        <span>Полный список ваших товаров</span>
                    </div>
                </div>
                <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'products' %}">Товары</a></li>
                    </ol>
                </div>
            </div>
            <div class="row">

                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Товары</h4>
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-primary mb-2" data-toggle="modal"
                                    data-target="#basicModal">
                                Добавить товар
                            </button>
                            <!-- Modal -->
                            <div class="modal fade" id="basicModal">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Добавить товар</h5>
                                            <button type="button" class="close" data-dismiss="modal">
                                                <span>&times;</span>
                                            </button>
                                        </div>

                                        <form action="{% url 'product_create' %}" method="post" name="products">
                                            {% csrf_token %}

                                            <div class="modal-body">
                                                <div class="row" id="products_modal">
                                                    {% for f in form %}
                                                        <div class="col-md-12 text-left text-dark mt-4">
                                                            {{ f.label_tag }}
                                                            {{ f|add_class:'form-control' }}
                                                        </div>
                                                    {% endfor %}
                                                    <div class="col-md-12 mt-4">
                                                        <h3>Уже имеется на складе</h3>
                                                    </div>
                                                    <div class="col-md-12 mt-3" id="delivery-1">
                                                        <div class="row">
                                                            <div class="col-md-12">
                                                                <label for="count">Количество</label>
                                                                <input type="number" class="form-control"
                                                                       name="delivery_count" required
                                                                       value="45" id="count">
                                                            </div>
                                                            <div class="col-md-12 mt-2">
                                                                <label for="id_warehouse">Склад</label>
                                                                <select name="warehouse" id="id_warehouse"
                                                                        class="form-control">
                                                                    {% for warehouse in warehouses %}
                                                                        <option value="{{ warehouse.id }}">{{ warehouse }}</option>
                                                                    {% endfor %}
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                            <div class="modal-footer">
                                                <button type="submit" class="btn btn-primary">
                                                    Сохранить
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="example" class="display" style="width:100%">
                                    <thead>
                                    <tr>
                                        <th>
                                            #
                                        </th>
                                        <th><strong>Название</strong></th>
                                        <th><strong>Артикуль</strong></th>
                                        <th><strong>Цена оптом</strong></th>
                                        <th><strong>Цена в розницу</strong></th>
                                        <th><strong>Выручка</strong></th>
                                        <th><strong>Количество продаж</strong></th>
                                        <th><strong>Осталось</strong></th>
                                        <th><strong>Удалить</strong></th>
                                        <th><strong>Распечатать</strong></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for product in products %}
                                        <tr>
                                            <td>
                                                {{ forloop.counter }}
                                            </td>
                                            <td>
                                                <a href="{% url 'product_detail' product.id %}?delivery_warehouse={{ warehouses.first.id }}">{{ product.title }}</a>
                                            </td>
                                            <td>{{ product.article }}</td>
                                            <td>{{ product.wholesale_price }}</td>
                                            <td>{{ product.retail_price }}</td>
                                            <td>{{ product.difference }}</td>
                                            <td>{{ product.purchased }}</td>
                                            <td>{{ product.remainder }}</td>
                                            <td>
                                                <button type="button" class="btn btn-danger btn-xs " data-toggle="modal"
                                                        data-target="#basicModal_product_{{ forloop.counter }}">
                                                    Удалить <i class="fa fa-trash-o"></i>
                                                </button>
                                                <!-- Modal -->
                                                <div class="modal fade" id="basicModal_product_{{ forloop.counter }}">
                                                    <div class="modal-dialog" role="document">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title">Удалить товар</h5>
                                                                <button type="button" class="close"
                                                                        data-dismiss="modal">
                                                                    <span>&times;</span>
                                                                </button>
                                                            </div>

                                                            <form action="{% url 'product_detail' product.id %}"
                                                                  method="post"
                                                                  name="products">
                                                                {% csrf_token %}
                                                                <input type="hidden" name="delete_product" value="yes">
                                                                <div class="modal-body">
                                                                    <h2>Вы уверены что хотите удалить товар ?</h2>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="submit" class="btn btn-primary"
                                                                            data-dismiss="modal">
                                                                        Отмена
                                                                    </button>
                                                                    <button type="submit" class="btn btn-danger">
                                                                        Удалить
                                                                    </button>
                                                                </div>
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <button class="btn btn-primary ml-3 btn-xs"
                                                        onclick="create_barcode('{{ product.article }}')">
                                                    Распечатать &nbsp; <i class="fa fa-paper-plane"></i>
                                                </button>
                                            </td>
                                        </tr>
                                        <svg class="d-none" id="barcode-{{ product.article }}"></svg>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
{% endblock %}

{% block extra_js %}
    <!-- Datatable -->
    <script src="{% static 'vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/plugins-init/datatables.init.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/jsbarcode@3.11.5/dist/barcodes/JsBarcode.code128.min.js"></script>
    <script>
        function create_barcode(article) {
            JsBarcode(`#barcode-${article}`, article.toString());

            let w = window.open('', 'printform', 'width=700,height=700');
            $(`#barcode-${article}`).removeAttr('class')
            let html2 = $(`#barcode-${article}`).prop('outerHTML');
            $(w.document.body).html(html2);
            w.print();
            w.close()
            location.reload(true)
        }
    </script>
    {#    <script>#}
    {#        function click() {#}
    {#            swal({#}
    {#                title: "Are you sure to delete ?",#}
    {#                text: "You will not be able to recover this imaginary file !!",#}
    {#                type: "warning",#}
    {#                showCancelButton: !0,#}
    {#                confirmButtonColor: "#DD6B55",#}
    {#                confirmButtonText: "Yes, delete it !!",#}
    {#                cancelButtonText: "No, cancel it !!",#}
    {#                closeOnConfirm: !1,#}
    {#                closeOnCancel: !1#}
    {#            }, function (e) {#}
    {#                e ? swal("Deleted !!", "Hey, your imaginary file has been deleted !!", "success") : swal("Cancelled !!", "Hey, your imaginary file is safe !!", "error")#}
    {#            })#}
    {#        }#}
    {#    </script>#}
    {#    <script src="{% static 'js/plugins-init/sweetalert.init.js' %}"></script>#}
    {#    <script>#}
    {#        document.querySelector(".sweet-wrong").onclick = function () {#}
    {#            sweetAlert("Oops...", "Something went wrong !!", "error")#}
    {#        }#}
    {#    </script>#}
{% endblock %}